package com.avoqado.pos.core.domain

/**
 * Los permisos EFECTIVOS que el server manda de verdad a esta app, por rol.
 *
 * 🔴 ARCHIVO GENERADO — NO LO EDITES A MANO. Se regenera con:
 * ```
 * node scripts/regenerar-permisos-reales.mjs          # reescribe este archivo
 * node scripts/regenerar-permisos-reales.mjs --check  # exit 1 si el server se movió
 * ```
 * El script llama `getEffectiveRolePermissions(rol, null)`
 * (`avoqado-server/src/lib/permissions.ts`) — exactamente la función con la que
 * `auth.mobile.service.ts` llena `venue.permissions` en el login, que es el campo
 * que esta app guarda en `SecureStorage.venuePermissions`.
 *
 * 🔴 POR QUÉ TIENE QUE SER LA LISTA COMPLETA: el server EXPANDE dependencias
 * implícitas antes de mandarla. `orders:update` arrastra `inventory:read`, así que
 * el CAJERO, el MESERO y la COCINA reciben `inventory:read` aunque nadie se los
 * concedió a mano. Un fixture recortado "con los permisos importantes" omite justo
 * esas entradas y deja pasar en verde un gate que en el aparato hace lo contrario.
 * Ya pasó: este archivo fue una vez una lista de 9 nombres titulada "los permisos
 * REALES".
 *
 * 🔴 QUÉ *NO* ES: no es la autoridad. La autoridad es la lista que llegó en el
 * login, y por eso los gates leen `SecureStorage.venuePermissions` y no un rol. Un
 * venue con Permission Sets (`VenueRolePermission`) manda otra cosa; aquí sale la
 * matriz por default (`customPermissions = null`), que es la de la mayoría.
 *
 * Derivado de avoqado-server@ad05bb37.
 */
object PermisosRealesDelServer {

    /** VIEWER — 17 permisos efectivos (16 declarados + 1 implícito: products:read). */
    val VIEWER = listOf(
        "analytics:read",
        "catalog-venue:read",
        "coupons:read",
        "customers:read",
        "discounts:read",
        "features:read",
        "home:read",
        "loyalty:read",
        "menu:read",
        "orders:read",
        "payments:read",
        "products:read",
        "referral:read",
        "reviews:read",
        "shifts:read",
        "teams:read",
        "upsells:read",
    )

    /** HOST — 19 permisos efectivos (16 declarados + 3 implícitos: analytics:read, payments:read, products:read). */
    val HOST = listOf(
        "analytics:read",
        "calendar:connect_self",
        "customers:create",
        "customers:read",
        "estimates:create",
        "home:read",
        "loyalty:read",
        "menu:read",
        "orders:read",
        "payments:read",
        "products:read",
        "referral:read",
        "reservations:cancel",
        "reservations:create",
        "reservations:read",
        "reservations:update",
        "tables:read",
        "tables:update",
        "teams:read",
    )

    /** KITCHEN — 12 permisos efectivos (8 declarados + 4 implícitos: analytics:read, inventory:read, payments:read, products:read). */
    val KITCHEN = listOf(
        "analytics:read",
        "area-tickets:deliver",
        "area-tickets:issue",
        "calendar:connect_self",
        "home:read",
        "inventory:read",
        "menu:read",
        "orders:read",
        "orders:update",
        "payments:read",
        "products:read",
        "scale:use",
    )

    /** WAITER — 49 permisos efectivos (42 declarados + 7 implícitos: analytics:read, estimates:create, inventory:read, products:read, shifts:close, shifts:create, tpv-time-entries:read). */
    val WAITER = listOf(
        "analytics:read",
        "area-tickets:deliver",
        "area-tickets:issue",
        "calendar:connect_self",
        "cash-out:view_own",
        "cash-out:withdraw",
        "commissions:view_own",
        "coupons:read",
        "coupons:redeem",
        "creditPacks:read",
        "creditPacks:redeem",
        "creditPacks:sell",
        "customers:create",
        "customers:read",
        "discounts:apply",
        "discounts:read",
        "estimates:create",
        "home:read",
        "inventory:read",
        "loyalty:read",
        "menu:read",
        "orders:cancel-unpaid",
        "orders:create",
        "orders:read",
        "orders:update",
        "payments:create",
        "payments:read",
        "products:read",
        "referral:read",
        "reviews:read",
        "scale:use",
        "serialized-inventory:create",
        "serialized-inventory:sell",
        "shifts:close",
        "shifts:create",
        "shifts:read",
        "tables:read",
        "tables:update",
        "teams:read",
        "tpv-payments:pay-later",
        "tpv-shifts:close",
        "tpv-shifts:create",
        "tpv-sim-custody:accept",
        "tpv-sim-custody:reject",
        "tpv-tables:assign",
        "tpv-time-entries:read",
        "tpv-time-entries:write",
        "tpv:read",
        "upsells:read",
    )

    /** CASHIER — 47 permisos efectivos (39 declarados + 8 implícitos: analytics:read, inventory:read, orders:create, products:read, shifts:close, shifts:create, tables:update, tpv-time-entries:read). */
    val CASHIER = listOf(
        "analytics:read",
        "area-tickets:checkout",
        "calendar:connect_self",
        "commissions:view_own",
        "coupons:read",
        "coupons:redeem",
        "creditPacks:read",
        "creditPacks:redeem",
        "creditPacks:sell",
        "customers:create",
        "customers:read",
        "discounts:apply",
        "discounts:read",
        "estimates:create",
        "home:read",
        "inventory:read",
        "loyalty:read",
        "menu:read",
        "orders:cancel-unpaid",
        "orders:create",
        "orders:read",
        "orders:update",
        "payments:create",
        "payments:read",
        "payments:refund",
        "products:read",
        "referral:read",
        "reviews:read",
        "serialized-inventory:create",
        "serialized-inventory:sell",
        "shifts:close",
        "shifts:create",
        "shifts:read",
        "tables:pay-any",
        "tables:read",
        "tables:update",
        "teams:read",
        "tpv-payments:pay-later",
        "tpv-products:read",
        "tpv-shifts:close",
        "tpv-shifts:create",
        "tpv-sim-custody:accept",
        "tpv-sim-custody:reject",
        "tpv-tables:assign",
        "tpv-time-entries:read",
        "tpv-time-entries:write",
        "upsells:read",
    )

    /** MANAGER — 137 permisos efectivos (122 declarados + 15 implícitos: customers:read, discounts:apply, discounts:read, estimates:create, features:update, orders:cancel-unpaid, orders:comp, orders:void, products:read, tables:pay-any, tpv-reports:read, tpv-settings:read, tpv-settings:update, tpv-shifts:close, tpv-shifts:create). */
    val MANAGER = listOf(
        "accounting:read",
        "analytics:export",
        "analytics:read",
        "area-tickets:cancel",
        "area-tickets:checkout",
        "area-tickets:configure",
        "area-tickets:confirm-external",
        "area-tickets:deliver",
        "area-tickets:issue",
        "calendar:connect_self",
        "calendar:view_status",
        "cash-out:read",
        "cash-out:report",
        "catalog-venue:read",
        "catalog-venue:request-override",
        "cfdi:issue",
        "cfdi:view",
        "commissions:read",
        "commissions:view_own",
        "coupons:*",
        "creditPacks:*",
        "customer-groups:*",
        "customers:*",
        "customers:read",
        "delivery-channels:read",
        "discounts:*",
        "discounts:apply",
        "discounts:read",
        "estimates:create",
        "features:read",
        "features:update",
        "features:write",
        "home:read",
        "inventory-transfers:approve",
        "inventory-transfers:dispatch",
        "inventory-transfers:read",
        "inventory-transfers:receive",
        "inventory-transfers:request",
        "inventory:adjust",
        "inventory:create",
        "inventory:delete",
        "inventory:read",
        "inventory:update",
        "loyalty:*",
        "menu:create",
        "menu:delete",
        "menu:read",
        "menu:update",
        "notifications:send",
        "orders:cancel",
        "orders:cancel-unpaid",
        "orders:comp",
        "orders:create",
        "orders:merge",
        "orders:read",
        "orders:update",
        "orders:void",
        "payment-link:create",
        "payment-link:read",
        "payment-link:update",
        "payments:create",
        "payments:read",
        "payments:refund",
        "payments:routing-read",
        "printers:manage",
        "printers:read",
        "products:read",
        "referral:fulfill-courtesy",
        "referral:override-existing-customer",
        "referral:read",
        "reports:read",
        "reservations:cancel",
        "reservations:create",
        "reservations:read",
        "reservations:update",
        "reviews:read",
        "reviews:respond",
        "role-config:read",
        "sale-verifications:review",
        "scale:configure",
        "scale:use",
        "serialized-inventory:create",
        "serialized-inventory:sell",
        "settlements:read",
        "settlements:simulate",
        "shifts:close",
        "shifts:create",
        "shifts:delete",
        "shifts:read",
        "shifts:update",
        "sim-custody:assign-to-promoter",
        "sim-custody:collect-from-promoter",
        "sim-custody:view-all-supervisors",
        "tables:manage-all",
        "tables:pay-any",
        "tables:read",
        "tables:update",
        "teams:create",
        "teams:delete",
        "teams:invite",
        "teams:read",
        "teams:update",
        "tender-types:read",
        "tpv-floor-elements:delete",
        "tpv-floor-elements:read",
        "tpv-floor-elements:write",
        "tpv-messages:read",
        "tpv-orders:comp",
        "tpv-orders:discount",
        "tpv-orders:void",
        "tpv-payments:pay-later",
        "tpv-payments:send-receipt",
        "tpv-products:read",
        "tpv-products:write",
        "tpv-reports:pay-later-aging",
        "tpv-reports:read",
        "tpv-settings:read",
        "tpv-settings:update",
        "tpv-shifts:close",
        "tpv-shifts:create",
        "tpv-sim-custody:accept",
        "tpv-sim-custody:reject",
        "tpv-tables:assign",
        "tpv-tables:delete",
        "tpv-tables:write",
        "tpv-time-entries:read",
        "tpv-time-entries:write",
        "tpv:command",
        "tpv:command:config",
        "tpv:command:lock",
        "tpv:command:maintenance",
        "tpv:command:restart",
        "tpv:create",
        "tpv:delete",
        "tpv:read",
        "tpv:update",
        "upsells:*",
    )

    /** ADMIN — 127 permisos efectivos (102 declarados + 25 implícitos: analytics:read, customers:read, discounts:apply, discounts:read, features:read, features:update, inventory:read, menu:read, orders:comp, orders:read, orders:update, orders:void, payments:read, products:read, serialized-inventory:create, settings:read, shifts:close, shifts:create, shifts:read, tables:read, tables:update, teams:read, tpv:read, venues:manage, venues:read). */
    val ADMIN = listOf(
        "accounting:manage",
        "accounting:read",
        "accounting:reconcile",
        "analytics:*",
        "analytics:read",
        "area-tickets:*",
        "billing:history:read",
        "billing:payment-methods:manage",
        "billing:payment-methods:read",
        "billing:read",
        "billing:subscriptions:manage",
        "billing:subscriptions:read",
        "calendar:connect_self",
        "calendar:disconnect_staff",
        "calendar:manage_venue",
        "calendar:view_status",
        "cash-out:manage",
        "cash-out:read",
        "cash-out:report",
        "catalog-venue:read",
        "catalog-venue:request-override",
        "cfdi:configure",
        "cfdi:issue",
        "cfdi:view",
        "commissions:approve",
        "commissions:create",
        "commissions:delete",
        "commissions:read",
        "commissions:update",
        "commissions:view_own",
        "coupons:*",
        "creditPacks:*",
        "customer-groups:*",
        "customers:*",
        "customers:read",
        "delivery-channels:manage",
        "delivery-channels:read",
        "delivery-channels:request",
        "discounts:*",
        "discounts:apply",
        "discounts:read",
        "estimates:create",
        "features:*",
        "features:read",
        "features:update",
        "home:*",
        "inventory-transfers:*",
        "inventory:*",
        "inventory:org-manage",
        "inventory:read",
        "loyalty:*",
        "menu:*",
        "menu:read",
        "notifications:*",
        "orders:*",
        "orders:comp",
        "orders:read",
        "orders:update",
        "orders:void",
        "payment-link:*",
        "payment:create-manual",
        "payments:*",
        "payments:read",
        "printers:*",
        "products:*",
        "products:read",
        "referral:configure",
        "referral:export-csv",
        "referral:fulfill-courtesy",
        "referral:override-existing-customer",
        "referral:read",
        "referral:void-manual",
        "reports:*",
        "reservations:*",
        "reviews:*",
        "role-config:*",
        "sale-verifications:review",
        "scale:*",
        "serialized-inventory:*",
        "serialized-inventory:change-category",
        "serialized-inventory:create",
        "settings:manage",
        "settings:read",
        "settlements:*",
        "shifts:*",
        "shifts:close",
        "shifts:create",
        "shifts:read",
        "sim-custody:reassign",
        "tables:*",
        "tables:read",
        "tables:update",
        "teams:*",
        "teams:read",
        "tender-types:*",
        "tpv-devices:manage",
        "tpv-floor-elements:delete",
        "tpv-floor-elements:read",
        "tpv-floor-elements:write",
        "tpv-kiosk:enable",
        "tpv-messages:read",
        "tpv-messages:send",
        "tpv-orders:comp",
        "tpv-orders:discount",
        "tpv-orders:void",
        "tpv-payments:send-receipt",
        "tpv-products:read",
        "tpv-products:write",
        "tpv-reports:export",
        "tpv-reports:pay-later-aging",
        "tpv-reports:read",
        "tpv-shifts:close",
        "tpv-shifts:create",
        "tpv-sim-custody:accept",
        "tpv-sim-custody:reject",
        "tpv-tables:assign",
        "tpv-tables:delete",
        "tpv-tables:write",
        "tpv-terminal:settings",
        "tpv-time-entries:read",
        "tpv-time-entries:write",
        "tpv:*",
        "tpv:read",
        "upsells:*",
        "venues:*",
        "venues:manage",
        "venues:read",
    )

    /** OWNER — 139 permisos efectivos (114 declarados + 25 implícitos: analytics:read, commissions:read, customers:read, discounts:apply, discounts:read, features:read, features:update, inventory:read, menu:read, orders:comp, orders:read, orders:update, orders:void, payments:read, products:read, settings:read, shifts:close, shifts:create, shifts:read, tables:read, tables:update, teams:read, tpv:read, venues:manage, venues:read). */
    val OWNER = listOf(
        "accounting:manage",
        "accounting:read",
        "accounting:reconcile",
        "activity:read",
        "analytics:*",
        "analytics:read",
        "area-tickets:*",
        "attendance:org-manage",
        "billing:history:read",
        "billing:payment-methods:manage",
        "billing:payment-methods:read",
        "billing:read",
        "billing:subscriptions:manage",
        "billing:subscriptions:read",
        "calendar:connect_self",
        "calendar:disconnect_staff",
        "calendar:manage_venue",
        "calendar:view_status",
        "cash-out:*",
        "catalog-venue:read",
        "catalog-venue:request-override",
        "cfdi:configure",
        "cfdi:issue",
        "cfdi:view",
        "commissions:*",
        "commissions:read",
        "coupons:*",
        "creditPacks:*",
        "customer-groups:*",
        "customers:*",
        "customers:read",
        "delivery-channels:manage",
        "delivery-channels:read",
        "delivery-channels:request",
        "discounts:*",
        "discounts:apply",
        "discounts:read",
        "estimates:create",
        "features:*",
        "features:read",
        "features:update",
        "financialConnections:*",
        "goals:org-manage",
        "home:*",
        "inventory-transfers:*",
        "inventory:*",
        "inventory:org-manage",
        "inventory:read",
        "loyalty:*",
        "manual-sales:create",
        "menu:*",
        "menu:read",
        "notifications:*",
        "orders:*",
        "orders:comp",
        "orders:read",
        "orders:update",
        "orders:void",
        "payment-link:*",
        "payment:create-manual",
        "payments:*",
        "payments:read",
        "printers:*",
        "products:*",
        "products:read",
        "referral:configure",
        "referral:export-csv",
        "referral:fulfill-courtesy",
        "referral:override-existing-customer",
        "referral:read",
        "referral:void-manual",
        "reports:*",
        "reservations:*",
        "reviews:*",
        "role-config:*",
        "sale-verifications:edit",
        "sale-verifications:reopen",
        "sale-verifications:review",
        "scale:*",
        "serialized-inventory:change-category",
        "serialized-inventory:create",
        "serialized-inventory:sell",
        "settings:manage",
        "settings:read",
        "settlements:*",
        "shifts:*",
        "shifts:close",
        "shifts:create",
        "shifts:read",
        "sim-custody:approve-registration",
        "sim-custody:assign-to-promoter",
        "sim-custody:assign-to-promoter-direct",
        "sim-custody:assign-to-supervisor",
        "sim-custody:collect-from-promoter",
        "sim-custody:collect-from-supervisor",
        "sim-custody:reassign",
        "sim-custody:view-all-supervisors",
        "tables:*",
        "tables:read",
        "tables:update",
        "teams:*",
        "teams:read",
        "tender-types:*",
        "tpv-devices:manage",
        "tpv-factory-reset:execute",
        "tpv-floor-elements:delete",
        "tpv-floor-elements:read",
        "tpv-floor-elements:write",
        "tpv-kiosk:enable",
        "tpv-messages:read",
        "tpv-messages:send",
        "tpv-orders:comp",
        "tpv-orders:discount",
        "tpv-orders:void",
        "tpv-payments:send-receipt",
        "tpv-products:read",
        "tpv-products:write",
        "tpv-reports:export",
        "tpv-reports:pay-later-aging",
        "tpv-reports:read",
        "tpv-settings:*",
        "tpv-shifts:close",
        "tpv-shifts:create",
        "tpv-sim-custody:accept",
        "tpv-sim-custody:reject",
        "tpv-tables:assign",
        "tpv-tables:delete",
        "tpv-tables:write",
        "tpv-terminal:settings",
        "tpv-time-entries:read",
        "tpv-time-entries:write",
        "tpv:*",
        "tpv:read",
        "upsells:*",
        "venue-crypto:manage",
        "venue-fiscal-profile:manage",
        "venues:*",
        "venues:manage",
        "venues:read",
    )

    /** SUPERADMIN — 1 permisos efectivos (4 declarados). */
    val SUPERADMIN = listOf(
        "*:*",
    )

    /** Los 9 roles por nombre EXACTO del enum `StaffRole` del server. */
    val PorRol: Map<String, List<String>> = mapOf(
        "VIEWER" to VIEWER,
        "HOST" to HOST,
        "KITCHEN" to KITCHEN,
        "WAITER" to WAITER,
        "CASHIER" to CASHIER,
        "MANAGER" to MANAGER,
        "ADMIN" to ADMIN,
        "OWNER" to OWNER,
        "SUPERADMIN" to SUPERADMIN,
    )

    /**
     * Lo que NADIE concedió a mano: `efectivos − declarados`.
     *
     * Está aquí para que un test pueda afirmar "esto llega por dependencia, no
     * porque alguien se lo diera" sin que nadie tenga que adivinarlo leyendo
     * `PERMISSION_DEPENDENCIES`. Es la mitad del fixture que la versión escrita a
     * mano se comió.
     */
    val ImplicitosPorRol: Map<String, List<String>> = mapOf(
        "VIEWER" to listOf(
            "products:read",
        ),
        "HOST" to listOf(
            "analytics:read",
            "payments:read",
            "products:read",
        ),
        "KITCHEN" to listOf(
            "analytics:read",
            "inventory:read",
            "payments:read",
            "products:read",
        ),
        "WAITER" to listOf(
            "analytics:read",
            "estimates:create",
            "inventory:read",
            "products:read",
            "shifts:close",
            "shifts:create",
            "tpv-time-entries:read",
        ),
        "CASHIER" to listOf(
            "analytics:read",
            "inventory:read",
            "orders:create",
            "products:read",
            "shifts:close",
            "shifts:create",
            "tables:update",
            "tpv-time-entries:read",
        ),
        "MANAGER" to listOf(
            "customers:read",
            "discounts:apply",
            "discounts:read",
            "estimates:create",
            "features:update",
            "orders:cancel-unpaid",
            "orders:comp",
            "orders:void",
            "products:read",
            "tables:pay-any",
            "tpv-reports:read",
            "tpv-settings:read",
            "tpv-settings:update",
            "tpv-shifts:close",
            "tpv-shifts:create",
        ),
        "ADMIN" to listOf(
            "analytics:read",
            "customers:read",
            "discounts:apply",
            "discounts:read",
            "features:read",
            "features:update",
            "inventory:read",
            "menu:read",
            "orders:comp",
            "orders:read",
            "orders:update",
            "orders:void",
            "payments:read",
            "products:read",
            "serialized-inventory:create",
            "settings:read",
            "shifts:close",
            "shifts:create",
            "shifts:read",
            "tables:read",
            "tables:update",
            "teams:read",
            "tpv:read",
            "venues:manage",
            "venues:read",
        ),
        "OWNER" to listOf(
            "analytics:read",
            "commissions:read",
            "customers:read",
            "discounts:apply",
            "discounts:read",
            "features:read",
            "features:update",
            "inventory:read",
            "menu:read",
            "orders:comp",
            "orders:read",
            "orders:update",
            "orders:void",
            "payments:read",
            "products:read",
            "settings:read",
            "shifts:close",
            "shifts:create",
            "shifts:read",
            "tables:read",
            "tables:update",
            "teams:read",
            "tpv:read",
            "venues:manage",
            "venues:read",
        ),
        "SUPERADMIN" to listOf(
        ),
    )
}
